src/Entity/Podcast.php
<?php

namespace App\Entity;

use App\Repository\PodcastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\NotBlank as Assert;

#[ORM\Entity(repositoryClass: PodcastRepository::class)]
class Podcast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert]
    private ?string $Titulo = null;

    #[ORM\ManyToOne(inversedBy: 'podcasts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $usuario = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $Fecha = null;

    #[ORM\Column(length: 610)]
    #[Assert]
    private ?string $descripcion = null;

    #[ORM\Column(type: Types::BINARY)]
    #[Assert]
    private $audio = null;

    #[ORM\Column(type: Types::BINARY)]
    #[Assert]
    private $imagen = null;

    #[ORM\Column(nullable: true)]
    private ?bool $favorito = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): self
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getFecha(): ?\DateTimeImmutable
    {
        return $this->Fecha;
    }

    public function setFecha(\DateTimeImmutable $Fecha): self
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getAudio()
    {
        return $this->audio;
    }

    public function setAudio($audio): self
    {
        $this->audio = $audio;

        return $this;
    }

    public function getImagen()
    {
        return $this->imagen;
    }

    public function setImagen($imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function isFavorito(): ?bool
    {
        return $this->favorito;
    }

    public function setFavorito(?bool $favorito): self
    {
        $this->favorito = $favorito;

        return $this;
    }
    public function __toString() {
        return $this->usuario;
        
    }
}

templates/index/_menu.html.twig
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
{% if app.user %} 
  <a class="navbar-brand" href="{{ path('app_index') }}">Mis podcasts</a>
  <button class="navbar-toggler p-0 border-0"
    type="button"
    data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
 
  
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
    <a class="nav-link"  href="{{ path('app_favorito') }}">
    Favoritos
    </a>
    </li>
    </ul>
     {% if is_granted('ROLE_ADMIN') %}

    <div class="d-md-flex my-2 my-lg-0">
      <a class="btn btn-outline-success mr-2 w-100" title="Gestión de usuarios" href="{{ path('app_usuario_index')}}">
        Usuarios
      </a>
      <a class="btn btn-outline-success mr-2 w-100" title="Gestión de podcasts" href="{{ path('app_podcast_admin')}}">
        Podcasts
      </a>
    </div>
      {% endif %}

    <div class="d-md-flex my-2 my-lg-0">
      <a class="btn btn-outline-success mr-2 w-100" title="Añadir podcast" href="{{ path('app_podcast_new')}}">
        <span class="oi oi-plus" title="añadir" aria-hidden="true"></span>
         Podcast
      </a>
    </div>
    <form class="form-inline">
        <input class="form-control mr-sm-2"
          type="text"
          placeholder="Buscar"
          aria-label="Search" />
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">
          Buscar
        </button>
      </form>

      {{include('usuario/_logout.html.twig')}}

 {% endif %}
  </div>
</nav>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block contenedor_principal %}
{% include 'comunes/_mensajes.html.twig' %}
    <div class="my-3 p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0">
    Mis podcasts
    </h6>

   
    {% for podcast in podcasts %}
      <div class="media text-muted pt-3">
        <svg width="32" height="32" class="mr-2 rounded">
          <rect width="32" height="32" style="fill:{{ podcast.imagen }};" />
        </svg>
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">  
          <div class="d-flex justify-content-between align-items-center w-100">
            <div> 
              <a href="app_podcast_show" target="_blank">
                <strong class="text-dark">{{ podcast.titulo }}</strong>
              </a>
              <span class="d-block">{{ podcast.descripcion }}</span>
            </div>
            <div class="d-flex">
               <a href="#"
                class="btn btn-link mg-3 favorito {{ podcast.favorito ? 'activo' }}" >
                <span class="oi oi-star" title="Favorito" aria-hidden="true"/>
              </a>
              <a href="{{ path('app_podcast_edit', {id: podcast.id}) }}" class="btn btn-link mg-3">
                <span class="oi oi-pencil" title="Edit" aria-hidden="true"></span>
              </a>

               {{ include('podcast/_delete_form.html.twig') }}

            </div>
        </div>
      </div>
      </div>
    {% else %} 
    <p>no podcasts found</p>
    {% endfor %}
  </div>
{% endblock %}